[tool.poetry]
name = "roboto"
version = "0.1.0"
description = "A type-hinted Telegram bot library."
authors = ["Tarcísio Eduardo Moreira Crocomo <tarcisioe@pm.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
validators = "^0.14.2"
pytest-cov = "^2.8.1"
aiohttp = "^3.6.2"
typing-extensions = "^3.7.4"
typing-inspect = "^0.5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
invoke = "^1.4.1"
isort = "^4.3.21"
flake8 = "^3.7.9"
pylint = "^2.4.4"
pylint-quotes = "^0.2.1"
mypy = "^0.770"
flake8-bugbear = "^20.1.4"

[tool.black]
skip_string_normalization = true

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
